stages:
  load_and_clean_gps_data:
    cmd: python src/load_and_clean_gps_data.py --config=params.yaml
    deps:
      - src/load_and_clean_gps_data.py
      - gps_data/FMS_signals_raw.csv
      - gps_data/raw_data
    outs:
      - gps_data/cleaned_data

  preprocess_gps_data:
    cmd: python src/preprocess_gps_data.py --config=params.yaml
    deps:
      - src/preprocess_gps_data.py
      - gps_data/cleaned_data
    outs:
      - gps_data/preprocessed_data

  merge_gps_data:
    cmd: python src/merge_gps_data.py --config=params.yaml
    deps:
      - src/preprocess_weather_data.py
      - gps_data/preprocessed_data/plant2-plant1
    outs:
      - gps_data/merge_data

  preprocess_weather_data:
    cmd: python src/preprocess_weather_data.py --config=params.yaml
    deps:
      - src/preprocess_weather_data.py
      - weather_data/raw_data
    outs:
      - weather_data/preprocessed_data
      - weather_data/cleaned_data

  merge_and_split_data:
    cmd: python src/merge_and_split.py --config=params.yaml
    deps:
      - src/merge_and_split.py
      - gps_data/merge_data/gps_data.csv
    outs:
      - merged_data/test.csv
      - merged_data/train.csv

