stages:
  load_and_clean_gps_data:
    cmd: python src/load_and_clean_gps_data.py --config=params.yaml
    deps:
      - src/load_and_clean_gps_data.py
      - gps_data/FMS_signals_raw.csv
      - gps_data/raw_data
    outs:
      - gps_data/cleaned_data